# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

obj-m += nvmap/
obj-m += host/nvdla/
obj-m += host/pva/
obj-m += tsec/
obj-m += dc/bridge/
obj-m += camera/
