# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

obj-m += ethernet/
obj-m += tegra_hv_net.o
ifdef CONFIG_CAN
obj-m += can/
endif
ifdef CONFIG_WLAN
obj-m += wireless/
endif
