# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

LINUXINCLUDE += -I$(srctree.nvidia)/drivers/gpu/host1x/hw/
LINUXINCLUDE += -I$(srctree.nvidia)/drivers/gpu/host1x/include
LINUXINCLUDE += -I$(srctree.nvidia)/include

nvhost-capture-objs = capture-support.o

obj-m += nvhost-capture.o
