# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

GCOV_PROFILE := y

LINUXINCLUDE += -I$(srctree)/drivers/platform/tegra/include \
							-I$(srctree.nvidia-oot)/drivers/platform/tegra/

obj-m += tegra23x_perf_uncore.o
