# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only

#
# NVPPS driver and PTP Framework.
#

obj-m += nvpps.o
nvpps-y += ../platform/tegra/ptp-notifier.o
nvpps-y += nvpps_main.o
