# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

# DT overlays
dtbo-y += tegra-optee.dtbo
dtbo-y += tegra194-carveouts.dtbo
dtbo-y += tegra194-jetson.dtbo
dtbo-y += tegra194-p3509-0000+p3668-0001-overlay.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-overlay.dtbo
dtbo-y += tegra234-jetson.dtbo
dtbo-y += tegra234-sbsa-uart.dtbo

# Nvidia internal DT platforms

# firespray DT
dtb-y += tegra234-p3710-0010-a01-linux-native.dtb
dtb-y += tegra234-p3710-0010-a04-linux-native.dtb
dtb-y += tegra234-p3710-0020-a01-linux-native.dtb

