# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

LINUXINCLUDE += -I$(srctree.nvidia-oot)/drivers/video/tegra/host
LINUXINCLUDE += -DCONFIG_TEGRA_HOST1X

obj-m += tegra_camera_platform.o
