# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

LINUXINCLUDE += -I$(srctree.nvidia-oot)/include

obj-m	+= cdi_gpio.o
obj-m	+= cdi_mgr.o
obj-m	+= cdi_dev.o
obj-m	+= cdi_pwm.o
obj-m 	+= cdi_tsc.o
